name: alnajm-core
# Running 'snapcraft register <name>' is advised
version: '1.14.6'
summary: Reference client of AlNajm, a peer-to-peer digital currency like Bitcoin.
description: |
  AlNajm is a community-driven cryptocurrency that was inspired by a Shiba Inu meme. The AlNajm Core software allows anyone to operate a node in the AlNajm blockchain networks and uses the Scrypt hashing method for Proof of Work. It is adapted from Bitcoin Core and other cryptocurrencies.

grade: stable
confinement: strict
base: core18
compression: lzo
architectures:
  - build-on: amd64
    run-on: amd64
  - build-on: arm64
    run-on: arm64
  - build-on: i386
    run-on: i386

apps:
  d:
    command: alnajmd
    plugs: [home, removable-media, network, network-bind]
    environment:
      # Override HOME so the datadir is located at ~/snap/alnajm-core/common/.alnajm/ instead of ~/snap/alnajm-core/current/.alnajm/, and each new version of the snap won't have a different data directory: https://docs.snapcraft.io/environment-variables/7983
      HOME: $SNAP_USER_COMMON
  qt:
    command: desktop-launch alnajm-qt
    plugs: [home, removable-media, network, network-bind, desktop, x11, unity7]
    environment:
      HOME: $SNAP_USER_COMMON
      DISABLE_WAYLAND: 1
  cli:
    command: alnajm-cli
    plugs: [home, removable-media, network]
    environment:
      HOME: $SNAP_USER_COMMON
  tx:
    command: alnajm-tx
    plugs: [home, removable-media, network]
    environment:
      HOME: $SNAP_USER_COMMON
  test:
    command: test_alnajm
    plugs: [home, removable-media, network]
    environment:
      HOME: $SNAP_USER_COMMON

parts:
  desktop-qt5:
    # So desktop-launch from qt5 is udsable
    # Adapted from https://github.com/ubuntu/snapcraft-desktop-helpers/blob/master/snapcraft.yaml
    source: https://github.com/ubuntu/snapcraft-desktop-helpers.git
    source-depth: 1
    source-subdir: qt
    source-commit: ec861254c2a1d2447b2c589446e6cdf04c75c260
    plugin: make
    make-parameters: ["FLAVOR=qt5"]
    build-packages:
      - build-essential
      - qtbase5-dev
      - dpkg-dev
    stage-packages:
      - libxkbcommon0
      - ttf-ubuntu-font-family
      - dmz-cursor-theme
      - light-themes
      - adwaita-icon-theme
      - gnome-themes-standard
      - shared-mime-info
      - libqt5gui5
      - libgdk-pixbuf2.0-0
      - libqt5svg5 # for loading icon themes which are svg
      - try: [appmenu-qt5] # not available on core18
      - locales-all
      - xdg-user-dirs
      - fcitx-frontend-qt5

  alnajm-core:
    plugin: nil
    override-build: |
      echo "This script is viewable at https://github.com/alnajm/alnajm/blob/master/contrib/snap/snapcraft.yaml"
      echo "Downloading files..."
      if [ "$SNAPCRAFT_ARCH_TRIPLET" = "i386-linux-gnu" ]; then # snap designates 32-bit as i386, but alnajm designates it as i686
        BUILD_ARCH_TRIPLET=i686-pc-linux-gnu
      else
        BUILD_ARCH_TRIPLET=$SNAPCRAFT_ARCH_TRIPLET
      fi
      wget https://github.com/alnajm/alnajm/releases/download/v${SNAPCRAFT_PROJECT_VERSION}/alnajm-${SNAPCRAFT_PROJECT_VERSION}-${BUILD_ARCH_TRIPLET}.tar.gz
      wget https://github.com/alnajm/gitian.sigs/archive/refs/heads/master.tar.gz
      tar -xvf master.tar.gz
      echo "Verifying secure hash matches signed values..."
      checksum=$(sha256sum alnajm-${SNAPCRAFT_PROJECT_VERSION}-${BUILD_ARCH_TRIPLET}.tar.gz)
      if ! (grep -r $checksum * | grep alnajm-${SNAPCRAFT_PROJECT_VERSION}-${BUILD_ARCH_TRIPLET}.tar.gz); then
        echo "Secure hash not verified."
        return
      else
        echo "Secure hash verified."
      fi
      tar -xvf alnajm-${SNAPCRAFT_PROJECT_VERSION}-${BUILD_ARCH_TRIPLET}.tar.gz
      echo "Running tests..."
      if ! (alnajm-${SNAPCRAFT_PROJECT_VERSION}/bin/test_alnajm); then
        echo "AlNajm tests failed."
        return
      else
        echo "AlNajm tests passed."
      fi
      wget https://raw.githubusercontent.com/alnajm/alnajm/v${SNAPCRAFT_PROJECT_VERSION}/doc/release-notes.md
      cat release-notes.md
      echo "Installing AlNajm Core..."
      echo "Version ${SNAPCRAFT_PROJECT_VERSION}"
      install -m 0755 -D -t $SNAPCRAFT_PART_INSTALL/bin alnajm-${SNAPCRAFT_PROJECT_VERSION}/bin/alnajmd
      if ! ([ "$BUILD_ARCH_TRIPLET" = "aarch64-linux-gnu" ]); then # there is no official alnajm-qt build on arm64
        install -m 0755 -D -t $SNAPCRAFT_PART_INSTALL/bin alnajm-${SNAPCRAFT_PROJECT_VERSION}/bin/alnajm-qt
      fi
      install -m 0755 -D -t $SNAPCRAFT_PART_INSTALL/bin alnajm-${SNAPCRAFT_PROJECT_VERSION}/bin/alnajm-cli
      install -m 0755 -D -t $SNAPCRAFT_PART_INSTALL/bin alnajm-${SNAPCRAFT_PROJECT_VERSION}/bin/alnajm-tx
      install -m 0755 -D -t $SNAPCRAFT_PART_INSTALL/bin alnajm-${SNAPCRAFT_PROJECT_VERSION}/bin/test_alnajm
      wget https://raw.githubusercontent.com/alnajm/alnajm/master/share/pixmaps/alnajm128.png
      install -m 0644 -D -t $SNAPCRAFT_PART_INSTALL/share/pixmaps alnajm128.png
    build-packages:
      - wget
    after:
      - desktop-qt5
